### ISSUE TITLE
Seem to have a race condition when signing in or out

### ISSUE THREAD

**Issue by TF123456** [chill117/express-mysql-session#76] opened 2017-11-17 21:09 UTC
I have a node express app with PassportJS Google strategy. When using the memory store I can sign in and out and the effect is immediately seen in the web page with no problem. When I enable express-mysql-session then a race condition becomes apparent:

When signing in the success redirect page will load saying that I still need to sign in, because req.session.passport.user is an empty object. Occasionally it will work properly and show the signed in user.

Step 1: go to home page
Step 2: click "sign in with Google"
Step 3: sign in with Google
Step 4: return to home page which still says I need to sign in
Step 5: If I now refresh the homepage I can see that I am signed in

As mentioned, sometimes step 4 does work properly and I see myself as signed in, hence my reason for suspecting a race.

Maybe I am doing something wrong to allow a race condition?

Here is the code:
```js
var express = require('express')
var glob = require('glob')

// ...
var passport = require('passport')
var session = require('express-session')
var mysql = require('mysql')
var MySQLStore = require('express-mysql-session')(session)
var GoogleStrategy = require('passport-google-oauth').OAuth2Strategy
var users = require('../app/models/users')
// ...

module.exports = function (app, config) {
  var env = process.env.NODE_ENV || 'development'
  app.locals.ENV = env
  app.locals.ENV_DEVELOPMENT = env === 'development'

  const azureConfig = {
  // ...
  }

  const localhostConfig = {
  // ...
  }

  var pool
  if (typeof process.env.deploy === 'undefined') {
    pool = mysql.createPool(localhostConfig)
  } else {
    pool = mysql.createPool(azureConfig)
  }

  var sessionStore = new MySQLStore({}/* session store options */, pool)

  // ...

  // ...
  app.use(session({
    secret: 'thesecret',
    resave: false,
    saveUninitialized: false,
    cookie: { httpOnly: true },
    store: sessionStore
  }))
  app.use(passport.initialize())
  app.use(passport.session())

  passport.use(new GoogleStrategy({
    clientID: 'redacted',
    clientSecret: 'redacted',
    callbackURL: 'callbackurl'
  },
  function (accessToken, refreshToken, profile, done) {
    users.findUserByExternalId('goog' + profile.id, function (user) {
      if (typeof user === 'undefined') {
        let displayName = profile.emails[0].value
        if (typeof profile.displayName !== "undefined" && profile.displayName.length !== 0) {
          displayName = profile.displayName
        }
        users.saveUser({externalId: 'goog' + profile.id, email: profile.emails[0].value, displayName: displayName}, (savedUser) => {
          return done(null, savedUser)
        })
      } else {
        return done(null, user)
      }
    })
  }
  ))

  passport.serializeUser(function (user, done) {
    done(null, user)
  })
  passport.deserializeUser(function (obj, done) {
    done(null, obj)
  })

  app.get('/auth/google', passport.authenticate('google', { scope: ['email'] }))
  app.get('/auth/google/callback',
    passport.authenticate('google', {failureRedirect: '/'}), function (req, res) {
      res.redirect('/dashboard')
    }
  )
  app.get('/auth/signout', function (req, res) {
    req.logout()
    res.redirect('/')
  })

  // ...

  return app
};
```

**Comment by TF123456** [comment] 2017-11-17 21:26
On further exploration this race condition seems to go away when I use a mysql connection rather than a pool... Why would that be?

**Comment by chill117** [comment] 2017-11-18 11:24
Well you have some asynchronous operations happening here:
* Authenticating the user via Google OAuth (to get an authorization token)
* Storing the session in the MySQL database (storing the Google authorization token)
Then:
* Getting the session from the MySQL database
* Checking the authorization token stored in your session object with Google

You must wait for each of these steps to complete before proceeding.

I don't think the issue you're experiencing is caused by this module. Instead I think the issue lies with the order in which you're using the different parts of the session+authentication setup. I haven't used passport recently, so I can't really help you there. You might have better luck bringing this issue to the [passport project](https://github.com/jaredhanson/passport) instead.

**Comment by TF123456** [comment] 2017-11-19 20:16
I agree with what you are saying. I just thought it strange that this only seems to happen when using a connection pool.

**Comment by rastomajernik** [comment] 2017-11-29 08:04
I am experiencing similar (or the same) symptoms using PassportJS Local strategy. While using the memory store evertything works properly, using express-mysql-session provides random results as far as log-in and log-out functionality is used.

... still could be a problem in the way how the sequence of calls is executed or problem in PassportJS.

**Comment by chill117** [comment] 2018-02-12 11:24
Did you all find a solution to this issue?

**Comment by rastomajernik** [comment] 2018-02-14 09:04
I removed PassportJS module from the project and implemented my own way of authentication. Then my express + express-session  + express-mysql-session setup works OK.

**Comment by chill117** [comment] 2018-02-14 11:14
I have done the same on previous projects. I tried using passport a few years back, but there were strange issues like the one here. I also solved it by removing passport and creating my own authentication middleware.

**Comment by chill117** [comment] 2018-05-11 09:12
Closing this as it has been resolved (out-of-scope for this project).

**Closed by chill117** 2018-05-11 09:12 UTC
